# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0002_auto_20170802_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
