# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0006_seccion_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='swachh_bharat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.PostModel')),
            ],
        ),
    ]
